FROM apache/superset:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY setup-psycopg2.sh /setup-psycopg2.sh
RUN chmod +x /setup-psycopg2.sh
ENTRYPOINT ["/setup-psycopg2.sh"]
USER superset
